/**
* This file was auto-generated by the Titanium Module SDK helper for Android
* Appcelerator Titanium Mobile
* Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
* Licensed under the terms of the Apache Public License
* Please see the LICENSE included with this distribution for details.
*
*/
package com.civico.tibeacons;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Intent;

@Kroll.module(name="Beacons", id="com.civico.tibeacons")
public class BeaconsModule extends KrollModule {

    public static final String TAG = "TiAPI";
    public static String API_URL;

    public BeaconsModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
        Log.e(TAG, "Started Civico-TiBeacons Module!");
    }

    @Kroll.method
    public void start(String apiUrl) {
        BeaconsModule.API_URL = apiUrl;

        try {
            Intent intent = new Intent(TiApplication.getInstance(), BeaconService.class);
            TiApplication.getInstance().startService(intent);
        } catch (Exception e) {
            Log.e(TAG, e.toString());
        }
    }
}
